In [28]:
import numpy as np

### Creating Numpy Arrays from Python Lists

In [29]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [30]:
[3.14 , 4 ,2,3]

[3.14, 4, 2, 3]

In [31]:
np.array([3.14 , 4 ,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [32]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [33]:
a1 = np.array([1,2,3,4])

In [34]:
type(a1)

numpy.ndarray

In [35]:
a2 = np.array([[1,2,3],
              [4,5,6]])

In [36]:
type(a2)

numpy.ndarray

In [37]:
a2.shape

(2, 3)

In [38]:
a2.ndim

2

In [39]:
a2.dtype

dtype('int32')

In [40]:
a2.size

6

### Creating Numpy Arrays from Scratch
`zeros`, `ones`, `arange`, `linspace`

In [41]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [45]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

`random`

In [24]:
np.random.random((4,4))

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

In [46]:
# Seed for reproducibility
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [47]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [49]:
np.random.randint(0, 10, (4,5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [50]:
np.random.rand(4,4)

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 , 0.6235101 ]])

## Array Indexing & Slicing

### One-dimensional subarray

In [51]:
x1 = np.random.randint(20, size=6)

In [52]:
x1

array([15, 13, 16, 17,  5,  9])

In [55]:
x1[4], x1[0], x1[-1]

(5, 15, 9)

## Multi-dimensional array

In [56]:
x2 = np.random.randint(10, size=(3,4))

In [57]:
x2

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]])

In [58]:
x2[0][0]

3

## Slicing
`x[start:stop:step]`

In [59]:
x1

array([15, 13, 16, 17,  5,  9])

In [64]:
x1[0:3], x1[2:4]

(array([15, 13, 16]), array([16, 17]))

In [65]:
# every other element, every 2 step
x1[::2]

array([15, 16,  5])

In [68]:
x2

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]])

In [69]:
x2[:2,:3]

array([[3, 0, 5],
       [1, 2, 4]])

In [70]:
x2[:,:2]

array([[3, 0],
       [1, 2],
       [0, 3]])

### Reshaping of Arrays & Transcope

In [71]:
grid = np.arange(1,10)
grid.shape

(9,)

In [72]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
x = np.array([1,2,3])

In [74]:
x.shape

(3,)

In [76]:
x.reshape((1,3)).shape

(1, 3)

In [77]:
x = np.array([[1.,2.],[3.,4.]])

In [78]:
x

array([[1., 2.],
       [3., 4.]])

In [79]:
x.T

array([[1., 3.],
       [2., 4.]])

### Array Concatenation and Splitting

In [80]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [82]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [84]:
grid = np.array([[1,2,3],
                 [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.concatenate((grid,grid)) # axix = 0 by default

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [87]:
np.concatenate((grid, grid), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [88]:
#vstack
x = np.array([1,2,3])

grid = np.array([[9,8,7],
                 [6,5,4]])

In [89]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [91]:
# horizontally stack the arrays: hstack
y = np.array([[99],
              [99]])
np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

### Splitting of arrays

In [92]:
x = np.array([1,2,3,99,89,3,2,1])

In [95]:
x1, x2, x3 = np.split(x, [3,5])

In [96]:
x1

array([1, 2, 3])

In [97]:
x2

array([99, 89])

In [98]:
x3

array([3, 2, 1])